Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
import pandas as pd
import requests
from bs4 import BeautifulSoup
Product_name=[]
Prices=[]
Description=[]
Reviews=[]

for i in range(2,12):
    url="https://www.flipkart.com/search?q=mobiles%20under%2030000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page="+ str(i)

    r = requests.get(url)

...     soup=BeautifulSoup(r.text, "lxml")
...     box=soup.find("div",class_="DOjaWF gdgoEp")
... 
... 
... 
...     names=box.find_all("div",class_="KzDlHZ")
... 
...     for i in names:
...         name=i.text
...         Product_name.append(name)
... 
... 
... 
...     prices=box.find_all("div",class_="Nx9bqj _4b5DiR")
... 
...     for i in prices:
...         name=i.text
...         Prices.append(name)
... 
... 
... 
...     desc=box.find_all("ul",class_="G4BRas")
... 
...     for i in desc:
...         name=i.text
...         Description.append(name)
... 
... 
... 
...     reviews=box.find_all("div",class_="_5OesEi")
... 
...     for i in reviews:
...         name=i.text
...         Reviews.append(name)
... 
... 
... print(len(Product_name), len(Prices), len(Description), len(Reviews))
... 
... df=pd.DataFrame({"Product_name":Product_name,"Prices":Prices,"Description":Description,"Reviews":Reviews})
... min_length = min(len(Product_name), len(Prices), len(Description), len(Reviews))
... data = zip(Product_name[:min_length], Prices[:min_length], Description[:min_length], Reviews[:min_length])
... df = pd.DataFrame(data, columns=["Product_name", "Prices", "Description", "Reviews"])
... 
... df.to_csv("E:/PYTHON PROJECT/flipkart_mobile_under_30000")
>>> [DEBUG ON]
>>> [DEBUG OFF]
